services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile   
    container_name: testapp
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy    
    env_file:
      - .env
    volumes:
      - ./logs:/backend/logs

  db:
    image: postgres:16
    container_name: testdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"                    
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:                       
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
